### ISSUE TITLE
build: TARGET=pi5 fails on main — test_io_malformed_unit.c uses mkstemp without a feature macro

### ISSUE THREAD

**Issue by geisten** [geisten/geistlib#244]
`make TARGET=pi5 bin` on a Pi 5 (Debian Trixie, gcc 14.2) fails since #230:

```
tests/test_io_malformed_unit.c:186:19: error: implicit declaration of function 'mkstemp'
```

`mkstemp` needs `_POSIX_C_SOURCE >= 200809L` (or `_GNU_SOURCE`) under `-std=c23`. `mk/target-linux.mk` defines `_GNU_SOURCE` since the 0.8.0 musl fix — `mk/target-pi5.mk` does not, and CI has no pi5-target leg, so the breakage shipped unseen (the ubuntu-24.04-arm job builds `TARGET=linux`).

Fix is one line, either way:
- `#define _POSIX_C_SOURCE 200809L` at the top of `tests/test_io_malformed_unit.c` (the pattern the other tests use, e.g. `test_spec_head_sampling_int.c`), or
- `_GNU_SOURCE` in `mk/target-pi5.mk` like the linux target.

The first is more precise; the second also inoculates the pi5 target against the next occurrence.

## Acceptance
- [ ] `make TARGET=pi5 bin` succeeds on a Pi 5 (verified on the reference board).
- [ ] Covered by test: the compile itself is the test once a CI leg builds `TARGET=pi5` — cheapest form: a cross-compile-only step (`make TARGET=pi5 CC=aarch64-linux-gnu-gcc-14 lib bin` or the existing arm64 runner with TARGET=pi5) so target-pi5 bit-rot fails in CI instead of on the board.
